#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-helper enable btrbak.timer >/dev/null || true
            deb-systemd-helper enable btrbak-snapshot-boot.service >/dev/null || true
            deb-systemd-invoke start btrbak.timer >/dev/null || true
        fi
        ;;
esac

exit 0
